name: trigger gitlab job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: ghcr.io/appleboy/gitlab-ci-action@v1.3.0
      with:
        token: ${{ secrets.GITLAB_PAT }}
        debug: true
        project_id: ${{ secrets.GITLAB_PROJECT_ID }}
        ref: ${{ guthub.head_ref }}
        variables: pr_num=${{ guthub.event.pull.request.number }}
    
     
        